# == == == == == === == == == == == #
#      Prison 3 Configuration       #
# Be sure to check your formatting! #
#      This must be valid yml.      #
# == == == == == === == == == == == #
#
#  New features have been recently added to prison.  These new features 
#  can add a lot of value to your server, but they may also be in the 
#  process of growing and evolving. If you experiance any issues, have
#  questions, or you have ideas on how to improve upon these items, 
#  then please visit our discord server.  These new features are 
#  marked with the "NEW" tag below.
#
#

# Note: This actually doesn't do anything. 
#       May have done something with v3.1.1 or earlier.
#debug: false

# Upon server startup prison will check to see if a newer version has been released.
check-updates: true

# Provides unidentifiable metrics so we can better understand what versions
# of minecraft, spigot, server OS, and the Prison plugin version that is 
# being used. This is used to understand what versions of spigot should be
# supported, and which versions of prison is actually being used and can
# greatly impact future development efforts. Enabling the 
# send-metrics would be greatly appreciatd since it will help us greatly.
# You can view the stats here: https://bstats.org/plugin/bukkit/Prison
send-metrics: true


# This will show prison based alerts, such as new versions of the plugin are available.
# If an alert is being shown, it can be disabled online by acknowledging it.
show-alerts: true

# NEW: Prison now has prestiges! 
# https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_107_setting_up_prestiges.md
# Note: "prestiges: true" is deprecated and will be removed in the future. 
prestiges: true

prestige:
  enabled: true
  resetMoney: true
  resetDefaultLadder: true

# NEW: This enables new physics to be applied when jumpping on slime blocks.
# When holding different items, like some block types or picks, the player can
# jump even higher to heights of 40 to 60+ blocks.
slime-fun: false

# NEW: Prison now has GUIs for most features and actions. For more options
# please check the GuiConfig.yml. 
# Access with /gui
prison-gui-enabled: true

# NEW: /prestige will open a confirmation GUI if this's on true, if on false 
# will use a chat confirmation instead.
prestige-confirm-gui: true

# There're more options for the GUIs, please edit the GuiConfig.yml


# NEW: Enable or disable the SellAll command and sub-commands
# New feature so setting to false since it will override other shop plugins.
sellall: true


# NEW: Enable backpacks integrated within prison.
backpacks: false


# NEW: Broadcast rankups and demotions to the whole server, in all worlds.
# If this value does not exist, or has a true value, it will be broadcasted.
# Any other value besides true, or non-existant, will be treated as false.
broadcast-rankups: false



# NEW: Startup testing of available blocks within prison. Tests three kinds of
# sources: Prison's BlockType, XMaterial's blocks (should mirror what's avaiable
# within spigot/bukkit, and the raw spigot/bukkit source.
# This should only be used to see what's available for the current version of 
# spigot that is running on the server. This will not provide any 
# extra blocks for any prison environment.
prison-block-compatibility-report: false



# NEW: Placeholder progress bar.  
# Can control how many segments are generated.  The more segments that
# are displayed the better reactive it will appear to the players.
# Also what is used for the postive and negative parts of the status bar,
# including color code and the text character to use. The color code will
# only apply once, not for each segment.
# You must quote the colors and segments or the yaml file can be fail to load.
placeholder:
  bar-segments: 20
  bar-positive-color: "&2"
  bar-positive-segment: "#"
  bar-negative-color: "&4"
  bar-negative-segment: "="




# NEW: Non-Functional at this time. Coming soon!
# This is strictly a work in progress right now, and does not work yet.
# This uses a new prison block model for providing the internal block lists
# and for generating the blocks.  This allows usage from mc 1.8.x through 
# v1.16.x and enables all new blocks for the version the server is running.
# This new model currently does not support custom blocks.
#use-new-prison-block-model: false



# Default language that is used as the primary language.
# See the lang directories under /plugins/Prison/module_conf/ for the 
# language files that can be edited.
default-language: en_US


# The storage engine that Prison should use to store data.
# Ensure that only one is left uncommented out. Also, ensure
# that you specify your MongoDB or SQL login credentials if necessary.
storageType: "json"
#storageType: "mongo"
#storageType: "sql"

# NOTE: The following is not used since SQL and MongoDB are not valid options.
# Login credentials for either SQL or MongoDB
#database:
#  enabled: false
#  type: sql # sql or mongo
#  host: localhost
#  database: prison
#  username: root
#  password: root
#  port: 3306



# NEW: 
# Prison mines reset gap is the number of milliseconds that are used to 
# space out the mine resets when starting the server.  This value should 
# not be changed unless you understand what you are doing. This value
# is converted to ticks, so should use 50 millisecond increments. If too 
# small of a value is used then it could produce a large amount of lag 
# if more than one mine tries to reset at the same time, or close to each
# other.  This may be changed to ticks in the near future.
#prison-mines-reset-gap: 5000

prison-mines:
  reset-gap-ms: 5000
  reset-paging:
    max-page-elapsed-time-ms: 75
    page-submit-delay-ticks: 1
    page-timeout-check-block-count: 250
    
